namespace Phantasma.RpcClient.Api
{
    public enum ApiMethods
    {
        getABI,
        getAccount,
        getApps,
        getAddressTransactions,
        getAddressTxCount,
        getAuctions,
        getAuctionsCount,
        getBlockByHash,
        getRawBlockByHash,
        getBlockByHeight,
        getRawBlockByHeight,
        getBlockHeight,
        getBlockTransactionCountByHash,
        getChains,
        getPeers,
        getPlatforms,
        getTransaction,
        getTransactionByBlockHashAndIndex,
        getTokens,
        getTokenData,
        getTokenTransfers,
        getTokenTransferCount,
        getSwapsForAddress,
        sendRawTransaction,
        lookUpName,
        invokeRawScript,
    }
}
